version: "2"
services:
  app:
    build:
      context: ./userservice
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./suggestit:/go/src/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: go
      POSTGRES_DB: godb
      POSTGRES_PASSWORD: abc123
    ports:
      - 5432:5432